### ISSUE TITLE
InterLap vs QuickSect

### ISSUE THREAD

**Issue by jdidion** [brentp/quicksect#12]
Hi @brentp, I started out using InterLap in a project, and am now looking to switch to QuickSect. In InterLap, the `closest()` method returns the nearest interval, which may be overlapping the query. On the other hand, QuickSect `left()` and `right()` methods return the nearest interval *not* overlapping the query.

For example, if I have a db with two intervals `[(1, 10), (1, 20)]`, calling `interlap.closest((15, 30))` returns `[(1, 20)]` whereas calling `itree.left(Interval(15, 30))` returns `[(1, 10)]`.

Is this difference between the two libraries intended? Is there anyway to replicate the behavior of InterLap in QuickSect?

Thanks!

**Comment by brentp** [comment]
hmm. that's probably an oversight on my part but interlap does lend itself more easily to this type of query. you could make your own closest function in quicksect by using `find(15, 30)` and then using left if that fails. Or you can use `itree.left((30, 31))`. Or, you could open a PR to provide a closest method for quicksect. There may be one in bx-python that you could borrow.
Sorry for the inconsistency, hope that helps.

**Comment by jdidion** [comment]
Ok, I'll work on adding this functionality and submit a PR. Closing this issue.
