### ISSUE TITLE
AttributeError exception when searching on an empty tree

### ISSUE THREAD

**Issue by muffato** [brentp/quicksect#2]
Hi,

Because `search` assumes `self.root` is defined (see https://github.com/brentp/quicksect/blob/master/src/quicksect.pyx#L76) searching in an empty tree (when `self.root` is still _None_) raises an _AttributeError_ exception.

It's not clear from the doc whether this is the intended behaviour
```python
>>> from quicksect import IntervalNode, Interval, IntervalTree                                                                                                                                    
>>> tree = IntervalTree()                                                                                                                                                                         
>>> tree.search(46, 47)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/quicksect.pyx", line 77, in quicksect.IntervalTree.search (src/quicksect.c:2669)
AttributeError: 'NoneType' object has no attribute 'intersect'
```

I think it would make sense to make `search` and `find` (and probably `left` and `right` too) return an empty list when searching in an empty tree. What do you think ?

Regards,
Matthieu

**Comment by brentp** [comment]
Yes. Can you open a PR?
