### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sebastian-luna-valero** [brentp/quicksect#9]
Hi,

We are discussing in https://github.com/cgat-developers/cgat-apps/issues/14 the problem below.

The code below runs fine:

```
from quicksect import IntervalNode, Interval, IntervalTree
tree3 = IntervalTree()
tree3.insert(Interval(22, 33, data='example1'))
tree3.right(Interval(44,55))
tree3.right(Interval(11,12))
tree3.left(Interval(44,55))
tree3.left(Interval(11,12))
```

The code below fails with `IndexError: list index out of range`

```
from quicksect import IntervalNode, Interval, IntervalTree
tree4 = IntervalTree()
tree4.insert(Interval(22, 33, data='example1'))
tree4.insert(Interval(22, 33, data='example2'))
tree4.right(Interval(44,55))
tree4.right(Interval(11,12))
tree4.left(Interval(44,55))
tree4.left(Interval(11,12))
```

Could you please let us know if it has an easy fix?

Best regards,
Sebastian

**Comment by brentp** [comment]
Thanks for the clear test. This was a simple fix. I have bumped the version and uploaded to pypi. let me know if you have any more problems.

**Comment by sebastian-luna-valero** [comment]
Great, many thanks!

I am now updating the bioconda package in https://github.com/bioconda/bioconda-recipes/pull/9990
